# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-28 18:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit_content', models.BooleanField(verbose_name='can edit content')),
                ('can_add_content', models.BooleanField(verbose_name='can add content')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collections.Category', verbose_name='category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'category permission',
                'verbose_name_plural': 'category permissions',
            },
        ),
        migrations.CreateModel(
            name='CollectionPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit_content', models.BooleanField(verbose_name='can edit content')),
                ('can_add_content', models.BooleanField(verbose_name='can add content')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collections.Collection', verbose_name='collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'collection permission',
                'verbose_name_plural': 'collection permissions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='collectionpermission',
            unique_together=set([('collection', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='categorypermission',
            unique_together=set([('category', 'user')]),
        ),
    ]
