# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-28 18:29
from __future__ import unicode_literals

import autoslug.fields
import cyclope.utils
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('order', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='order')),
            ],
            options={
                'ordering': ('order', '-id'),
                'verbose_name': 'categorization',
                'verbose_name_plural': 'categorizations',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from=b'name', unique=True)),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'get_latest_by': 'pk',
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
            bases=(models.Model, cyclope.utils.ThumbnailMixin),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from=b'name')),
                ('visible', models.BooleanField(default=True, verbose_name='visible')),
                ('navigation_root', models.BooleanField(default=False, verbose_name='navigation root')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('default_list_view', models.CharField(blank=True, default=b'', max_length=255, verbose_name='default list view')),
                ('view_options', jsonfield.fields.JSONField(default=b'{}')),
                ('content_types', models.ManyToManyField(db_index=True, to='contenttypes.ContentType', verbose_name='content types')),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collections',
            },
            bases=(models.Model, cyclope.utils.ThumbnailMixin),
        ),
        migrations.AddField(
            model_name='category',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='collections.Collection', verbose_name='collection'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='collections.Category', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='categorization',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorizations', to='collections.Category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='categorization',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('collection', 'name')]),
        ),
    ]
