# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-08 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('threadedcomments', '0003_threadedcomment_newest_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomComment',
            fields=[
                ('threadedcomment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='threadedcomments.ThreadedComment')),
                ('subscribe', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
            bases=('threadedcomments.threadedcomment',),
        ),
    ]
