# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-28 18:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='object')),
                ('status', models.CharField(choices=[(b'REP', 'reported'), (b'HOLD', 'on hold'), (b'IGN', 'ignored'), (b'DEL', 'deleted')], default=b'REP', max_length=4, verbose_name='status')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type')),
            ],
            options={
                'verbose_name': 'abuse report',
                'verbose_name_plural': 'abuses reports',
            },
        ),
        migrations.CreateModel(
            name='AbuseReportElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='object')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'abuse report elements',
                'verbose_name_plural': 'abuses reports elements',
            },
        ),
        migrations.CreateModel(
            name='AbuseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'abuse types',
                'verbose_name_plural': 'abuses types',
            },
        ),
        migrations.AddField(
            model_name='abusereportelement',
            name='abuse_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abuse.AbuseType', verbose_name='abuse type'),
        ),
        migrations.AddField(
            model_name='abusereportelement',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AddField(
            model_name='abusereportelement',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abuse.AbuseReport'),
        ),
        migrations.AddField(
            model_name='abusereportelement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='abusereportelement',
            unique_together=set([('user', 'content_type', 'object_id')]),
        ),
    ]
