# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-28 18:29
from __future__ import unicode_literals

import autoslug.fields
import cyclope.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyclope', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from=b'name', unique=True)),
                ('published', models.BooleanField(default=True, verbose_name='published')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('allow_comments', models.CharField(choices=[(b'SITE', 'default'), (b'YES', 'enabled'), (b'NO', 'disabled')], default=b'SITE', max_length=4, verbose_name='allow comments')),
                ('show_author', models.CharField(choices=[(b'AUTHOR', 'author'), (b'USER', 'user if author is empty'), (b'SITE', 'default')], default=b'SITE', help_text='Select which field to use to show as author of this content.', max_length=6, verbose_name='show author')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cyclope.Author', verbose_name='author')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cyclope.Source', verbose_name='source')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
            },
            bases=(models.Model, cyclope.utils.ThumbnailMixin),
        ),
        migrations.CreateModel(
            name='ExternalContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from=b'name', unique=True)),
                ('published', models.BooleanField(default=True, verbose_name='published')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('allow_comments', models.CharField(choices=[(b'SITE', 'default'), (b'YES', 'enabled'), (b'NO', 'disabled')], default=b'SITE', max_length=4, verbose_name='allow comments')),
                ('show_author', models.CharField(choices=[(b'AUTHOR', 'author'), (b'USER', 'user if author is empty'), (b'SITE', 'default')], default=b'SITE', help_text='Select which field to use to show as author of this content.', max_length=6, verbose_name='show author')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('content_url', models.CharField(max_length=100, verbose_name='content url')),
                ('new_window', models.BooleanField(default=False, verbose_name='open in new window')),
                ('skip_detail', models.BooleanField(default=False, verbose_name='skip detailed view')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cyclope.Author', verbose_name='author')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cyclope.Source', verbose_name='source')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'external content',
                'verbose_name_plural': 'external contents',
            },
            bases=(models.Model, cyclope.utils.ThumbnailMixin),
        ),
        migrations.CreateModel(
            name='FlashMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from=b'name', unique=True)),
                ('published', models.BooleanField(default=True, verbose_name='published')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('allow_comments', models.CharField(choices=[(b'SITE', 'default'), (b'YES', 'enabled'), (b'NO', 'disabled')], default=b'SITE', max_length=4, verbose_name='allow comments')),
                ('show_author', models.CharField(choices=[(b'AUTHOR', 'author'), (b'USER', 'user if author is empty'), (b'SITE', 'default')], default=b'SITE', help_text='Select which field to use to show as author of this content.', max_length=6, verbose_name='show author')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cyclope.Author', verbose_name='author')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cyclope.Source', verbose_name='source')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'flash movie',
                'verbose_name_plural': 'flash movies',
            },
            bases=(models.Model, cyclope.utils.ThumbnailMixin),
        ),
        migrations.CreateModel(
            name='MovieClip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from=b'name', unique=True)),
                ('published', models.BooleanField(default=True, verbose_name='published')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('allow_comments', models.CharField(choices=[(b'SITE', 'default'), (b'YES', 'enabled'), (b'NO', 'disabled')], default=b'SITE', max_length=4, verbose_name='allow comments')),
                ('show_author', models.CharField(choices=[(b'AUTHOR', 'author'), (b'USER', 'user if author is empty'), (b'SITE', 'default')], default=b'SITE', help_text='Select which field to use to show as author of this content.', max_length=6, verbose_name='show author')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cyclope.Author', verbose_name='author')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cyclope.Source', verbose_name='source')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'movie clip',
                'verbose_name_plural': 'movie clips',
            },
            bases=(models.Model, cyclope.utils.ThumbnailMixin),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from=b'name', unique=True)),
                ('published', models.BooleanField(default=True, verbose_name='published')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('allow_comments', models.CharField(choices=[(b'SITE', 'default'), (b'YES', 'enabled'), (b'NO', 'disabled')], default=b'SITE', max_length=4, verbose_name='allow comments')),
                ('show_author', models.CharField(choices=[(b'AUTHOR', 'author'), (b'USER', 'user if author is empty'), (b'SITE', 'default')], default=b'SITE', help_text='Select which field to use to show as author of this content.', max_length=6, verbose_name='show author')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cyclope.Author', verbose_name='author')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cyclope.Source', verbose_name='source')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'picture',
                'verbose_name_plural': 'pictures',
            },
            bases=(models.Model, cyclope.utils.ThumbnailMixin),
        ),
        migrations.CreateModel(
            name='RegularFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from=b'name', unique=True)),
                ('published', models.BooleanField(default=True, verbose_name='published')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('allow_comments', models.CharField(choices=[(b'SITE', 'default'), (b'YES', 'enabled'), (b'NO', 'disabled')], default=b'SITE', max_length=4, verbose_name='allow comments')),
                ('show_author', models.CharField(choices=[(b'AUTHOR', 'author'), (b'USER', 'user if author is empty'), (b'SITE', 'default')], default=b'SITE', help_text='Select which field to use to show as author of this content.', max_length=6, verbose_name='show author')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cyclope.Author', verbose_name='author')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cyclope.Source', verbose_name='source')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
            },
            bases=(models.Model, cyclope.utils.ThumbnailMixin),
        ),
        migrations.CreateModel(
            name='SoundTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from=b'name', unique=True)),
                ('published', models.BooleanField(default=True, verbose_name='published')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('allow_comments', models.CharField(choices=[(b'SITE', 'default'), (b'YES', 'enabled'), (b'NO', 'disabled')], default=b'SITE', max_length=4, verbose_name='allow comments')),
                ('show_author', models.CharField(choices=[(b'AUTHOR', 'author'), (b'USER', 'user if author is empty'), (b'SITE', 'default')], default=b'SITE', help_text='Select which field to use to show as author of this content.', max_length=6, verbose_name='show author')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cyclope.Author', verbose_name='author')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cyclope.Source', verbose_name='source')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sound track',
                'verbose_name_plural': 'sound tracks',
            },
            bases=(models.Model, cyclope.utils.ThumbnailMixin),
        ),
    ]
