# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-28 18:29
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyclope', '0001_initial'),
        ('collections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from=b'name')),
                ('last_sent_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='sent date')),
                ('view', models.CharField(default=b'default', max_length=255, verbose_name='view')),
                ('regions', models.CharField(choices=[(b'c', 'only central'), (b'tc', 'top and central'), (b'cl', 'central and lateral'), (b'tcl', 'top, central and lateral')], default=b'c', max_length=4, verbose_name='regions')),
                ('n_contents_top', models.IntegerField(default=0, help_text='Number of categorized contents to show in the top region.', verbose_name='top')),
                ('n_contents_center', models.IntegerField(default=10, help_text='Number of categorized contents to show in the central region.', verbose_name='center')),
                ('n_contents_lateral', models.IntegerField(default=0, help_text='Number of categorized contents to show in the lateral region.', verbose_name='lateral')),
                ('head_image', models.ImageField(blank=True, help_text='select image for head: 720px width x 124px height', null=True, upload_to=b'theme/images', verbose_name='header newsletter')),
                ('show_title', models.BooleanField(default=True, verbose_name='show title name in header')),
                ('show_ToC', models.BooleanField(default=False, verbose_name='show table of contents')),
                ('header', models.TextField(blank=True, help_text='Text that will always be added on top of the content.', verbose_name='header')),
                ('sender_name', models.CharField(blank=True, default=b'', help_text='name that will displayed as the sender of the newsletter.', max_length=40, verbose_name='sender name')),
                ('sender', models.EmailField(help_text='e-mail address that will be used to send the newsletter.', max_length=254, verbose_name='sender e-mail')),
                ('test_recipients', models.CharField(help_text='comma separated list of test e-mail addresses', max_length=255, verbose_name='test recipients')),
                ('recipients', models.CharField(help_text='comma separated list of recipient e-mail addresses', max_length=255, verbose_name='recipients')),
                ('list_admin', models.CharField(blank=True, help_text='creates a shortcut to the administrator of your mailing list (full url with http://)', max_length=255, verbose_name='url list manager')),
                ('content_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collections.Category')),
                ('layout', models.ForeignKey(help_text='Layout to use to build the resulting HTML.', on_delete=django.db.models.deletion.CASCADE, to='cyclope.Layout', verbose_name='layout')),
            ],
            options={
                'verbose_name': 'newsletter',
                'verbose_name_plural': 'newsletters',
            },
        ),
    ]
