# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-08 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_id', models.PositiveIntegerField(db_index=True)),
                ('other_id', models.PositiveIntegerField(db_index=True)),
                ('order', models.IntegerField(blank=True, db_index=True, null=True)),
                ('other_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_contents_rt', to='contenttypes.ContentType', verbose_name='content type')),
                ('self_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_contents_lt', to='contenttypes.ContentType', verbose_name='content type')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'series content',
                'verbose_name_plural': 'series contents',
            },
        ),
    ]
